[workspace]
resolver = "2"

members = [
    "pallets/template",
    "runtime",
    "node"
]

[profile.release]
panic = "unwind"
opt-level = 3

[profile.production]
inherits = "release"
lto = true
codegen-units = 1